<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>AI Search · TravelSite.lk</title><link rel="stylesheet" href="assets/admin.css"></head><body>
<aside><div class="logo">✈ <span>travelsite.lk</span><small>ADMIN</small></div><nav><a href="?page=dashboard">Dashboard</a><a href="?page=destinations">Destinations</a><a href="?page=providers">Affiliate Providers</a><a class="on" href="?page=ai-search">AI Search</a><span>Trips</span><span>Clicks & Conversions</span><span>CMS & SEO</span><span>Site Settings</span><span>Admin Users</span><span>Audit Log</span></nav><a class="logout" href="?page=logout">Sign out</a></aside>
<section class="shell"><header><div><b>AI Search</b><small>Planner configuration</small></div><div><?=e($_SESSION['admin_name'])?> · <?=e($_SESSION['admin_role'])?></div></header><main>
<div class="title"><div><h1>AI Search Settings</h1><p>Configure how the future travel planner interprets requests. This page does not activate an AI endpoint yet.</p></div></div>
<?php if($notice):?><div class="alert"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<form method="post" class="panel formgrid"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="save">
<label class="toggle wide"><input type="checkbox" name="enabled" <?=$config['enabled']?'checked':''?>> Enable AI search when the public integration is installed</label>
<label>AI provider code<input name="provider" maxlength="40" value="<?=e($config['provider'])?>" required><small>The API key belongs in server configuration, never here.</small></label>
<label>Model identifier<input name="model" maxlength="100" value="<?=e($config['model'])?>" placeholder="Set when provider integration is installed"></label>
<label>Default origin airport<input name="default_origin" minlength="3" maxlength="3" value="<?=e($config['default_origin'])?>" required></label>
<label>Default currency<input name="default_currency" minlength="3" maxlength="3" value="<?=e($config['default_currency'])?>" required></label>
<label>Destination suggestion limit<input type="number" name="max_destinations" min="1" max="20" value="<?=e($config['max_destinations'])?>" required></label>
<label>Results per product type<input type="number" name="max_results" min="1" max="50" value="<?=e($config['max_results'])?>" required></label>
<label>Budget interpretation<select name="budget_mode"><option value="total_trip" <?=$config['budget_mode']==='total_trip'?'selected':''?>>Total trip</option><option value="per_person" <?=$config['budget_mode']==='per_person'?'selected':''?>>Per person</option></select></label>
<fieldset><legend>Search types</legend><?php foreach(['flight'=>'Flights','hotel'=>'Hotels','tour'=>'Tours','package'=>'Itinerary packages'] as $key=>$label):?><label class="toggle"><input type="checkbox" name="search_types[]" value="<?=$key?>" <?=in_array($key,$config['search_types'],true)?'checked':''?>> <?=$label?></label><?php endforeach;?></fieldset>
<label class="toggle"><input type="checkbox" name="recommendations" <?=$config['recommendations']?'checked':''?>> Suggest destinations</label><label class="toggle"><input type="checkbox" name="package_builder" <?=$config['package_builder']?'checked':''?>> Assemble itinerary options</label>
<label class="wide">System instructions<textarea name="system_prompt" maxlength="10000" rows="10" required><?=e($config['system_prompt'])?></textarea><small>Explain budget, family needs, estimated prices and affiliate booking boundaries. Do not paste secrets or personal data.</small></label>
<div class="wide actions"><button type="submit" <?=in_array($_SESSION['admin_role']??'', ['super_admin','admin'],true)?'':'disabled'?>>Save AI settings</button></div></form>
<?php if($versions):?><section class="panel" style="margin-top:20px"><h2>Recent prompt versions</h2><p>Restoring a version keeps a new copy in history.</p><div class="tablewrap"><table><thead><tr><th>Version</th><th>Saved</th><th></th></tr></thead><tbody><?php foreach($versions as $version):?><tr><td>#<?=e($version['id'])?></td><td><?=e($version['created_at'])?></td><td><?php if(in_array($_SESSION['admin_role']??'', ['super_admin','admin'],true)):?><form method="post" onsubmit="return confirm('Restore this prompt version?')"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="restore"><input type="hidden" name="version_id" value="<?=e($version['id'])?>"><button type="submit">Restore</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
</main></section></body></html>
